language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    beta
    nightly
before_install:
  - rustup component add rustfmt
script:
  - cargo fmt -- --check
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
