language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - beta
    - nightly
before_install:
  - sudo apt-get update
  - sudo apt-get -y install pkg-config
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
  - cargo clippy --verbose --workspace
